-- Generated from generator/demo_specs/aws-indonesia-palm-oil-eudr.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-palm-oil-eudr
-- This is the schema that is actually deployed for ID_PALM_OIL_EUDR.

-- Alerts fire on the bottom tail of EUDR Compliant Lots
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_EUDR_COMPLIANT_LOTS) AS T
  FROM RAW.SATELLITE_ALERTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_EUDR_COMPLIANT_LOTS <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_EUDR_COMPLIANT_LOTS), 2) AS AVG_EUDR_COMPLIANT_LOTS,
  ROUND(AVG(f.KPI_DEFORESTATION_FREE), 2) AS AVG_DEFORESTATION_FREE,
  ROUND(AVG(f.KPI_FOREST_PROXIMITY_RISK), 2) AS AVG_FOREST_PROXIMITY_RISK,
  ROUND(AVG(f.KPI_PLOTS_GEOLOCATED), 2) AS AVG_PLOTS_GEOLOCATED
FROM RAW.SATELLITE_ALERTS f
JOIN RAW.COMPLIANCE_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_EUDR_COMPLIANT_LOTS), 2) AS AVG_EUDR_COMPLIANT_LOTS,
  ROUND(AVG(f.KPI_DEFORESTATION_FREE), 2) AS AVG_DEFORESTATION_FREE,
  ROUND(AVG(f.KPI_FOREST_PROXIMITY_RISK), 2) AS AVG_FOREST_PROXIMITY_RISK,
  ROUND(AVG(f.KPI_PLOTS_GEOLOCATED), 2) AS AVG_PLOTS_GEOLOCATED
FROM RAW.SATELLITE_ALERTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_EUDR_COMPLIANT_LOTS) AS KPI_EUDR_COMPLIANT_LOTS, AVG(KPI_DEFORESTATION_FREE) AS KPI_DEFORESTATION_FREE, AVG(KPI_PLOTS_GEOLOCATED) AS KPI_PLOTS_GEOLOCATED, AVG(KPI_FOREST_PROXIMITY_RISK) AS KPI_FOREST_PROXIMITY_RISK FROM RAW.SATELLITE_ALERTS),
     en AS (SELECT SUM(KPI_SMALLHOLDERS_MAPPED) AS KPI_SMALLHOLDERS_MAPPED, SUM(KPI_DUE_DILIGENCE_STATEMENTS) AS KPI_DUE_DILIGENCE_STATEMENTS, SUM(KPI_SATELLITE_ALERTS_30D) AS KPI_SATELLITE_ALERTS_30D FROM RAW.COMPLIANCE_DOCS)
  SELECT 1 AS SORT_ORDER, 'EUDR Compliant Lots' AS TITLE, KPI_EUDR_COMPLIANT_LOTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EUDR_COMPLIANT_LOTS)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Deforestation-Free' AS TITLE, KPI_DEFORESTATION_FREE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DEFORESTATION_FREE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Smallholders Mapped' AS TITLE, KPI_SMALLHOLDERS_MAPPED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_SMALLHOLDERS_MAPPED) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Due Diligence Statements' AS TITLE, KPI_DUE_DILIGENCE_STATEMENTS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_DUE_DILIGENCE_STATEMENTS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Plots Geolocated' AS TITLE, KPI_PLOTS_GEOLOCATED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PLOTS_GEOLOCATED), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Satellite Alerts (30d)' AS TITLE, KPI_SATELLITE_ALERTS_30D AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SATELLITE_ALERTS_30D)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Forest Proximity Risk' AS TITLE, KPI_FOREST_PROXIMITY_RISK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FOREST_PROXIMITY_RISK), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
