-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for EUDR Compliance Engine
-- ============================================================================
USE DATABASE PALM_OIL_EUDR;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: ALERT_FALSE_POSITIVE_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.ALERT_FALSE_POSITIVE_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PLOT_DEFORESTATION_CHECK'),
  SERIES_COLNAME => 'PROVINCE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.ALERT_FALSE_POSITIVE_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.ALERT_FALSE_POSITIVE_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PLOT_DEFORESTATION_CHECK'), SERIES_COLNAME => 'PROVINCE', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

