-- ============================================================================
-- 99_RESET.SQL — Reset EUDR Compliance Engine to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_EUDR;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_SATELLITE SUSPEND;
ALTER TASK IF EXISTS APP.TASK_CHECK_POLYGONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_DDS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PLOT_DEFORESTATION_CHECK REFRESH;
ALTER DYNAMIC TABLE CURATED.SHIPMENT_COMPLIANCE_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.DDS_GENERATION_QUEUE REFRESH;
ALTER DYNAMIC TABLE CURATED.RISK_HEATMAP REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_EUDR.RAW.PLOT_POLYGONS → 15000
-- SELECT COUNT(*) FROM PALM_OIL_EUDR.RAW.SATELLITE_ALERTS → 100000
-- SELECT COUNT(*) FROM PALM_OIL_EUDR.RAW.DUE_DILIGENCE_STATEMENTS → 3000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_DDS RESUME;
ALTER TASK IF EXISTS APP.TASK_CHECK_POLYGONS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_SATELLITE RESUME;
